version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8181:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/umbrel/umbrel/my-configs/jenkins-config:/var/jenkins_home  # Ваш путь для конфигурации
      - /var/run/docker.sock:/var/run/docker.sock